config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'

  resources :documents, only: %i[show index] do
    member do
      get 'preshow'
    end
  end

  post '/webhooks/stripe' => 'stripe_webhooks#handle_event'

  get 'purchased_documents', to: 'pages#purchased_documents', as: :purchased_documents
  post '/purchase_document/:document_id', to: 'documents#purchase_intent', as: :purchase_document
  get 'purchase_complete', to: 'purchase_complete#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
end

app/views/pages/home.html.erb
<div class="container">
  <header class="centered">
    <h1 class="document-title">Download your LPO in seconds</h1>
    <h3>Please insert the Cadastral reference number of your property in the textfield below.</h3>
  </header>

  <%= form_for :document, url: documents_path, method: :get do |f| %>
    <div class="form-field centered">
      <%= f.text_field :cadastral_reference, placeholder: 'Enter Cadastral Reference Number', class: 'text-input' %>
      <%= f.submit 'Submit', class: 'submit-button' %>
    </div>
  <% end %>
</div>

app/views/pages/purchased_documents.html.erb
<div class="document-container">
  <header>
    <h1 class="document-title">Purchased LPOs</h1>
    <% if @documents.any? %>
      <h3>We only save a the last 5 LPOs you purchase.</h3>
      <h3>Download them if you don't want to have to buy them again.</h3>
    <% else %>
      <h3>At the moment you do not have any LPOs.</h3>
      <%= link_to "Press Here to find your Property's LPO",root_path %>
    <% end %>
  </header>

  <main>
    <% if @documents.any? %>
      <table class="document-table">
        <thead>
          <tr>
            <th>Property Address</th>
            <th>Cadastral</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @documents.each do |document| %>

              <tr class="document-row">
                <td class="document-address">
                  <%= document.address[0..30]... %>
                </td>
                <td class="document-cadastral">
                  <%= document.cadastral_reference %>
                </td>
                <td class="document-action">
                  <%= link_to "Download", document_path(document, format: :pdf), target: '_blank', class: 'download-button' %>
                </td>
              </tr>

          <% end %>
        </tbody>
      </table>
      <div class="back-link-container">
        <%= link_to "Purchase another LPO", root_path, class: 'back-link' %>
      </div>
    <% end %>
  </main>
</div>