config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'

  resources :documents, only: %i[show index] do
    member do
      get 'preshow'
    end
  end

  post '/webhooks/stripe' => 'stripe_webhooks#handle_event'

  get 'purchased_documents', to: 'pages#purchased_documents', as: :purchased_documents
  post '/purchase_document/:document_id', to: 'documents#purchase_intent', as: :purchase_document
  get 'purchase_complete', to: 'purchase_complete#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
end

app/models/document.rb
# frozen_string_literal: true

class Document < ApplicationRecord
  validates :cadastral_reference, presence: true
  validates :year, presence: true, length: { maximum: 255 }
  validates :address, presence: true, length: { maximum: 255 }
end

app/controllers/documents_controller.rb
# frozen_string_literal: true

class DocumentsController < ApplicationController
  def index
    cadastral_reference = params[:document][:cadastral_reference]
    document = Document.find_by(cadastral_reference: cadastral_reference)

    unless document
      scraped_data = scrape_website(cadastral_reference)

      document = Document.create(
        cadastral_reference: cadastral_reference,
        year: scraped_data[:year],
        address: scraped_data[:address],
        template_id: rand(1..5)
      )
    end
    redirect_to preshow_document_path(document)
  end

  def preshow
    @document = Document.find(params[:id])
  end

  def show
    authenticate_user(params[:id])

    if (document = Document.find_by(id: params[:id]))
      @document = document

      respond_to do |format|
        format.html
        format.pdf do
          if current_user && current_user.purchased_documents.include?(params[:id].to_i)
            render pdf: 'show' # Excluding ".pdf" extension.
          end
        end
      end
    else
      redirect_to root_path
    end
  end

  def purchase_intent
    document_id = params[:document_id].to_i
    amount_in_cents = 4900 # Adjust this based on your requirements
    purchase_token = SecureRandom.hex(16)

    current_user.update(purchase_token: purchase_token)

    stripe_service = StripeService.new(current_user)
    intent = stripe_service.create_payment_intent(amount_in_cents, document_id, request.base_url)

    redirect_to intent.url, allow_other_host: true
  end

  private

  def scrape_website(cadastral_reference)
    page_url = "https://www1.sedecatastro.gob.es/cycbieninmueble/OVCConCiud.aspx?UrbRus=U&RefC=#{cadastral_reference}&esBice=&RCBice1=&RCBice2=&DenoBice=&from=OVCBusqueda&pest=rc&RCCompleta=5628108UF2452N0005QU&final=&del=29&mun=69"

    page_content = RestClient.get(page_url)
    parsed_content = Nokogiri::HTML(page_content)

    year = parsed_content&.css('.control-label.black.text-left')&.at(5)&.children&.last&.text&.strip || 'N/A'
    adr_1 = parsed_content&.css('.control-label.black.text-left')&.at(6)&.children&.first&.presence&.text&.strip || ''
    adr_2 = parsed_content&.css('.control-label.black.text-left')&.at(6)&.children&.last&.presence&.text&.strip || ''

    address = "#{adr_1} #{adr_2}".strip.upcase.presence || 'N/A'

    {
      year: year,
      address: address
    }
  end

  def authenticate_user(id = nil)
    redirect_to new_user_registration_path(document_id: id) unless current_user
  end
end

app/helpers/documents_helper.rb
# frozen_string_literal: true

module DocumentsHelper
end

app/views/documents/preshow.html.erb
<% if @document.address == 'N/A' %>
  <div class="content-container">
    <div class="content">
      <h1>This LPO does not exist.</h1>
      <h3>We can't find a property with Cadastral ID: <%= @document.cadastral_reference %></h3>
      <h3>Please Retry.</h3>
      <div class="link-back">
        <%= link_to "Click here to search for another LPO", root_path %>
      </div>
    </div>
  </div>
<% else %>
  <div class="content-container">
    <div class="content">
      <h1 style="">✅</h1>
      <h4>Your LPO exists, and it is ready to download.</h4>
      <h3>Cadastral ID: <%= @document.cadastral_reference %></h3>
      <h2><%= @document.address %></h2>

      <% if current_user %>
        <%= link_to "Go to Download Page", document_path(@document), class: "action-button" %>
      <% else %>
        <%= link_to "Sign up to purchase LPO", new_user_registration_path(document_id: params[:id]), class: "action-button" %>
      <% end %>

      <div class="link-back">
        <%= link_to "Back home", root_path %>
      </div>
    </div>
  </div>
<% end %>

app/views/documents/show.html.erb
<div class="content-container">
  <div class="content">

    <% if params[:payment] == 'retry' %>
      <h1>🔁</h1>
      <h4 class="alert">There was something wrong with your payment.</h4>
      <h4 class="alert">You must retry.</h4>
    <% else %>
      <h1>✅</h1>
      <h4>Your document is ready.</h4>
    <% end %>

    <p>Cadastral Ref: <%= @document.cadastral_reference %></p>
    <h5>Licencia Primera Ocupacion</h5>
    <h4><%= @document.address %></h4>

    <%= form_with url: purchase_document_path(@document.id), method: :post do |form| %>
      <%= form.submit "Purchase it here for 49€", class: "action-button" %>
    <% end %>

    <div class="link-back">
      <%= link_to "Back home", root_path %>
    </div>
  </div>
</div>

app/views/documents/show.pdf.erb
<%= wicked_pdf_stylesheet_link_tag "pdfs/commons" -%>
<%= wicked_pdf_stylesheet_link_tag "pdfs/template_#{@document.template_id}" -%>
<%= wicked_pdf_stylesheet_link_tag "commons" -%>
<%= render "documents/pdf_templates/template_#{@document.template_id}" %>